apiVersion: batch/v1
kind: CronJob
metadata:
  name: leaderboard-update-cronjob
spec:
  timeZone: "{{ .Values.handleLeaderBoardUpdate.timeZone }}"
  schedule: "{{ .Values.handleLeaderBoardUpdate.schedule }}"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: leaderboard-update-cronjob
              image: {{ .Values.nest_app.image.repository }}:{{ .Values.nest_app.image.tag }}
              command: ["node", "dist/main.js", "handleLeaderBoardUpdate"]
              envFrom:
                - configMapRef:
                    name: nest-app-config
          restartPolicy: OnFailure