apiVersion: v1
kind: Service
metadata:
  name: nest-app
spec:
  type: {{ .Values.nest_app_service.type }}
  selector:
    app: nest-app
  ports:
  - protocol: TCP
    port: {{ .Values.nest_app_service.ports.port }}
    targetPort: {{ .Values.nest_app_service.ports.targetPort }}
